db:
  build: ./MySQL/
  environment:
    MYSQL_ROOT_PASSWORD: root
wordpress:
  build: ./WordPress/
  ports:
    - 8080:80
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: root
  links:
    - db
  volumes:
    -  ./blog:/var/www/html/wp-content/themes